package my.vaadin.app;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BookFormDesign extends FormLayout {
	protected TextField title;
	protected TextField author;
	protected Button save;
	protected Button delete;

	public BookFormDesign() {
		Design.read(this);
	}
}
